--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 8/17/2017 4:36:10 PM
-- Server version: 5.7.19-log
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE cameracookbookapp;

--
-- Definition for table camera_ingredients
--
DROP TABLE IF EXISTS camera_ingredients;
CREATE TABLE camera_ingredients (
  ID VARCHAR(255) NOT NULL,
  user_suggested_name VARCHAR(255) DEFAULT NULL,
  dominant_color VARCHAR(255) DEFAULT NULL,
  contour_shape VARCHAR(255) DEFAULT NULL,
  shape_vertices DECIMAL(10, 0) DEFAULT NULL,
  cusine VARCHAR(255) DEFAULT NULL,
  no_of_contours INT(11) DEFAULT NULL,
  red_value DECIMAL(10, 0) DEFAULT NULL,
  green_value DECIMAL(10, 0) DEFAULT NULL,
  blue_value VARCHAR(255) DEFAULT NULL,
  use_frequency TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;